In [1]:
import numpy as np
import pandas as pd

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [2]:
#creating a matrix with columns of the output matrix are powers of the input vector
a=np.array([1,2,3,4,5])     #creating array
N=len(a)                    #length of array means value of N
matrix=np.column_stack(a**(N-i-1) for i in range (N))
matrix

<ipython-input-2-fe5327a53bb1>:4: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  matrix=np.column_stack(a**(N-i-1) for i in range (N))


array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [3]:
#Using Vandermonde Function
matrix1=np.vander(a, N, increasing=False)
matrix1

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [4]:
input=[10,20,30,40,50,60,70,80,90,100]
def mov_avg(input, n=4):
    asum=np.cumsum(input, dtype=float)    #summing up all the values one by one
    asum[n:]=asum[n:]-asum[:-n]            #substracting the number to the result
    return asum[n-1:]/n
print(mov_avg)

l=np.array(input)
np.array(mov_avg(l,n=4))

<function mov_avg at 0x0000025125C27790>


array([25., 35., 45., 55., 65., 75., 85.])

In [5]:
#Using pandas library
s=pd.DataFrame(input)
s.rolling(4).mean().dropna()

0
3  25.0
4  35.0
5  45.0
6  55.0
7  65.0
8  75.0
9  85.0

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
mylist

[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [7]:
def mov_avg(mylist, n=3):
    asum=np.cumsum(mylist, dtype=float)    #summing up all the values one by one
    asum[n:]=asum[n:]-asum[:-n]            #substracting the number to the result
    return asum[n-1:]/n
mov_avg

<function __main__.mov_avg(mylist, n=3)>

Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [8]:
b=np.array(mylist)
np.array(mov_avg(b,n=3))

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [9]:
#Using pandas library
x=pd.DataFrame(mylist)
x.rolling(3).mean().dropna()

0
2     5.000000
3     4.666667
4     5.666667
5     6.666667
6     9.666667
7    28.666667
8    49.333333
9    72.666667
10   84.000000
11   93.333333
12  116.333333